repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.271
    hooks:
      - id: ruff
  - repo: https://github.com/ambv/black
    rev: 24.4.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: forbid-new-submodules
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
